### ISSUE TITLE
Replace LuaXe with native OCaml solution

### ISSUE THREAD

**Issue by PeyTy** [PeyTy/LuaXe#64]
https://github.com/demigodaarts/haxe-llvm
This repo would be used to implement native Haxe code generator of Lua.
https://github.com/jdonaldson/haxe also implemented in parallel, but with a different vision.

Issues in this repo would be closed in meaning of OCaml version of generator.

JS GENERATOR IS IMPOSSIBLE TO WRITE FULL FEATURED!
AVE OCAML!

**Comment by jdonaldson** [comment]
Come on over to the haxe_lua branch!  I've only just started there, so there's not much vision.  I just pick something that doesn't work and try to make it work.

**Comment by PeyTy** [comment]
@jdonaldson https://github.com/PeyTy/haxe/tree/lua
I am working on it right now :)

**Comment by PeyTy** [comment]
@jdonaldson got almost full syntax support, working on OOP and Std

**Comment by PeyTy** [comment]
@jdonaldson I will commit soon to my fork

**Comment by jdonaldson** [comment]
Nice!  I'll be eager to check it out.  I'm pretty confident we'll have a solid Lua target at the end of this, one way or another.

**Comment by Simn** [comment]
I like where this is going!

**Comment by PeyTy** [comment]
I made OCaml generator mostly backwards compatible with LuaXe (magic, metas, OOP, std, etc). I think it is important for LuaXe users.

I will push to HaxeFoundation repo as soon as possible, when it will on-pair with LuaXe generator, so everyone will have a chance to download it from nightly builds and to replace LuaXe with it.

Also, now it is much easier to implement feature requests!

Interested anyone?

**Comment by sonygod** [comment]
when can I have a test? sound great!

**Comment by PeyTy** [comment]
Hello @sonygod ! You can rebuild manually from https://github.com/PeyTy/haxe/tree/lua (very easily indeed, http://haxe.org/documentation/introduction/building-haxe.html)

BUT PLEASE WAIT I WILL PUSH LATEST CHANGES AND NOTIFY YOU!

**Comment by PeyTy** [comment]
cc @sonygod https://github.com/PeyTy/haxe/tree/lua Enjoy!

**Comment by PeyTy** [comment]
@jdonaldson I think after some work you could just swap to my version and continue your vim plugin project. We can somehow combine our solutions. Checkout my repo, I mean, try to write some useful Haxe code. Is it already near-ready to be used in little-beta production?

**Comment by PeyTy** [comment]
@jdonaldson many tests failed because of low level Lua weirdness. High level stuff and Std mostly works. I really failed in Enum and Switch implementation, and must fix them quickly :))

**Comment by jdonaldson** [comment]
Yeah, I would like to get back to the plugin project soon.  But, I don't want to leave the lua project abruptly in an unfinished state.  I think we'll run into trickier problems with some of these edge case unit tests.  In that case, I think it'll be really good to have two people thinking about solutions.

I know that the haxe foundation folks really liked the commit messages in my lua branch.  I think it'll be a good series of changes for other devs to follow for their own targets... I believe it even helped you get your own lua branch started.  To that end, I think it makes sense to have those early changes in the official haxe foundation repo.

From what I've seen in our repos I also know that we do things slightly differently on certain syntax features.  I think that may end up being a good thing though, it's good to consider multiple solutions for tricky cases.  

My proposal is to try and get our two projects to pass as many unit tests as possible in the next few weeks.  I think we're both fairly close to having > 80% coverage.  We can compare the passing/failing tests, as well as the generated output.  I think that'll shed some light on which techniques are covering the most cases.  I also want Simn to take a look at how we're going about things, and offer general advice.  After that, we can work on haxe-lua as a normal project... e.g. we don't need to add the same lengthy comments to each commit as I had been doing... we can just add small notes.  I also promise not to force-push anymore and break the public commit chain ;)

It'll be great to work with someone else on this, I'm looking forward to it.

**Comment by PeyTy** [comment]
Hello @dazKind ! I recommend you to write directly on @jdonaldson e-mail. He rarely looks into GitHub notifications. You may ask for amount of % passed unit tests. This will be a solid indicator of stability.

**Comment by jdonaldson** [comment]
Hey folks, sorry for being unresponsive.  Let me know if there's some other threads I'm missing.

My other target is still under progress, and it slowed down a lot recently due to some really dramatic work/life changes (new baby, major changes at work).

That said, I'm still making steady progress.  My hope was to merge my work with Oleg's once Haxe 3.2 is out of RC.  Sorry this is taking longer than I planned.

**Comment by PeyTy** [comment]
@jdonaldson wow! congratulations! let me know when you`ll need my help

**Comment by dazKind** [comment]
@jdonaldson congratz! 

So, I tested a bit more involving a more complex sample and Im seeing a couple of errors related to ambigous syntax e.g.
```lua
	 --[[ Vars --]] local this1;
	 --[[ Binop --]] this1 = lua.Boot.defArray({[0]=0, 0, 0 }, 3);
	 --[[ Binop --]] self.m_origin = this1;
	 --[[ Binop --]] self.m_planes = Array.new();
	 --[[ Binop --]] self.m_corners = Array.new();
	 --[[ Vars --]] local _g = 0;
	 --[[ While --]] while (_g < 6) do 
		 --[[ Vars --]] local i = (function() local __x = _g
		_g = _g + 1 return __x end)();
		 --[[ Call --]] self.m_planes:push((function() 
			local r0
			local this2
			(function() this2 = lua.Boot.defArray({[0]=0, 1, 0, 1 }, 4) return this2 end)()
			(function() r0 = this2 return r0 end)() -- FATAL ERROR: ambiguous syntax (function call x new statement) near '('
			return r0
		end )());
```

and an occassional doubled semi-colon e.g.
```lua
enhaxe.math.MathUtils.round = function(x) 
	 --[[ Return --]] do return Std["int"]((function() 
		local r0
		if (x > 0) then 
		 --[[ Binop --]] r0 = x + .5; elseif (x < 0) then 
		 --[[ Binop --]] r0 = x - .5;; else r0 = 0; end -- FATAL ERROR:  unexpected symbol near ';'
		return r0
	end )()) end;
end
```
Now if I fix those errors by hand it runs and I see the expected output! It's almost usable on my end :)

**Comment by PeyTy** [comment]
@jdonaldson Would be great if you allowed me write-access to your repo. I would make little fixes to std, and genlua, without bothering you with pull requests and waiting. I will not do any breaking changes

@dazKind can you provide source code of this issue? I fixed semicolons problem in my own independent genlua https://github.com/PeyTy/haxe implementation, probably I can fix this here

**Comment by dazKind** [comment]
@PeyTy I just gave the unittests in @jdonaldson's fork a shot. 
Both mentioned errors and a few more can be found in the resulting `unit.lua`.
I guess it is better to use this as a poper baseline instead of testing against random code chunks.

**Comment by jdonaldson** [comment]
@PeyTy  done!

If you see something really strange that I've done in the resulting lua output, let's talk about it.  My goal on the first pass here was to structure the code as close as possible to what is happening in haxe.  This means the lua code is pretty strange and difficult to read, and is not at all like lua code written by hand.

Once we get decent unit test coverage, I wanted to experiment with some different ways of generating lua statements, etc.

**Comment by PeyTy** [comment]
@jdonaldson *yyyyeeeeahhh!*

**Comment by jdonaldson** [comment]
I was working on Reflect.callMethod... still not completely happy with it, but it lets some of the unit tests work properly now.  Just pushed one more update.
